version: "3"
services:

  app:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    command: bash -c "dotnet restore && dotnet build && dotnet run  --urls http://+:5000"
    working_dir: /app
    volumes:
      - ./net5:/app
    ports:
      - "5000:5000"

  agent:
    image: grafana/agent:v0.30.2
    volumes:
      - ./agent.yaml:/etc/agent/agent.yaml