version: "3"
services:

  dotnet5:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    command: bash -c "dotnet restore && dotnet build && dotnet run  --urls http://+:5000"
    working_dir: /app
    volumes:
      - ./net5:/app
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://agent:4317

  dotnet6:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    command: bash -c "dotnet restore && dotnet build && dotnet run  --urls http://+:5001"
    working_dir: /app
    volumes:
      - ./net6:/app
    ports:
      - "5001:5001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://agent:4317

  agent:
    image: grafana/agent:v0.30.2
    volumes:
      - ./agent.yaml:/etc/agent/agent.yaml